-- =========================================================
-- Living Abroad MVP
-- PostgreSQL 16.x
-- Flyway migration: V1__init_living_abroad_schema.sql
-- =========================================================

CREATE TABLE countries (
    country_code       VARCHAR(3) PRIMARY KEY,
    country_name_ko    VARCHAR(50) NOT NULL,
    country_name_en    VARCHAR(100) NOT NULL,
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE visa_programs (
    visa_program_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code       VARCHAR(3) NOT NULL,
    program_code       VARCHAR(50) NOT NULL,
    program_name_ko    VARCHAR(100) NOT NULL,
    program_name_en    VARCHAR(150) NOT NULL,
    official_url       TEXT,
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_visa_programs_program_code UNIQUE (program_code),
    CONSTRAINT fk_visa_programs_country
        FOREIGN KEY (country_code) REFERENCES countries (country_code)
        ON DELETE RESTRICT
);

CREATE TABLE users (
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(255) NOT NULL,
    password_hash      VARCHAR(255) NOT NULL,
    user_name          VARCHAR(50) NOT NULL,
    account_status     VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_account_status
        CHECK (account_status IN ('ACTIVE', 'INACTIVE', 'WITHDRAWN'))
);

CREATE TABLE user_profiles (
    profile_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                    BIGINT NOT NULL,
    age                        SMALLINT NOT NULL,
    education_level            VARCHAR(30) NOT NULL,
    major                      VARCHAR(100),
    current_occupation         VARCHAR(150) NOT NULL,
    experience_years           NUMERIC(4, 1) NOT NULL DEFAULT 0,
    language_test_type         VARCHAR(30),
    language_score             NUMERIC(6, 2),
    available_funds_krw        BIGINT NOT NULL DEFAULT 0,
    family_accompanied         BOOLEAN NOT NULL DEFAULT FALSE,
    preferred_country_code     VARCHAR(3),
    career_description         TEXT,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_profiles_preferred_country
        FOREIGN KEY (preferred_country_code) REFERENCES countries (country_code)
        ON DELETE SET NULL,
    CONSTRAINT ck_user_profiles_age CHECK (age BETWEEN 18 AND 70),
    CONSTRAINT ck_user_profiles_experience CHECK (experience_years BETWEEN 0 AND 60),
    CONSTRAINT ck_user_profiles_funds CHECK (available_funds_krw >= 0)
);

CREATE TABLE analyses (
    analysis_id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                            BIGINT NOT NULL,
    analysis_status                    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    input_age                          SMALLINT NOT NULL,
    input_education_level              VARCHAR(30) NOT NULL,
    input_major                        VARCHAR(100),
    input_current_occupation           VARCHAR(150) NOT NULL,
    input_experience_years             NUMERIC(4, 1) NOT NULL DEFAULT 0,
    input_language_test_type           VARCHAR(30),
    input_language_score               NUMERIC(6, 2),
    input_available_funds_krw          BIGINT NOT NULL DEFAULT 0,
    input_family_accompanied           BOOLEAN NOT NULL DEFAULT FALSE,
    input_preferred_country_code       VARCHAR(3),
    input_career_description           TEXT NOT NULL,
    model_version                      VARCHAR(50),
    data_version                       VARCHAR(50),
    requested_at                       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at                       TIMESTAMPTZ,
    error_message                      TEXT,
    CONSTRAINT fk_analyses_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_analyses_preferred_country
        FOREIGN KEY (input_preferred_country_code) REFERENCES countries (country_code)
        ON DELETE SET NULL,
    CONSTRAINT ck_analyses_status
        CHECK (analysis_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_analyses_age CHECK (input_age BETWEEN 18 AND 70),
    CONSTRAINT ck_analyses_experience CHECK (input_experience_years BETWEEN 0 AND 60),
    CONSTRAINT ck_analyses_funds CHECK (input_available_funds_krw >= 0)
);

CREATE TABLE analysis_country_results (
    result_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id                BIGINT NOT NULL,
    visa_program_id            BIGINT NOT NULL,
    rank_position              SMALLINT NOT NULL,
    total_score                NUMERIC(5, 2) NOT NULL,
    rule_score                 NUMERIC(5, 2) NOT NULL,
    environment_score          NUMERIC(5, 2) NOT NULL,
    career_similarity_score    NUMERIC(5, 2) NOT NULL,
    preference_score           NUMERIC(5, 2) NOT NULL,
    eligibility_status         VARCHAR(20) NOT NULL,
    result_summary             TEXT,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analysis_results_analysis
        FOREIGN KEY (analysis_id) REFERENCES analyses (analysis_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_analysis_results_visa_program
        FOREIGN KEY (visa_program_id) REFERENCES visa_programs (visa_program_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_analysis_results_program UNIQUE (analysis_id, visa_program_id),
    CONSTRAINT uq_analysis_results_rank UNIQUE (analysis_id, rank_position),
    CONSTRAINT ck_analysis_results_rank CHECK (rank_position BETWEEN 1 AND 3),
    CONSTRAINT ck_analysis_results_total_score CHECK (total_score BETWEEN 0 AND 100),
    CONSTRAINT ck_analysis_results_rule_score CHECK (rule_score BETWEEN 0 AND 100),
    CONSTRAINT ck_analysis_results_environment_score CHECK (environment_score BETWEEN 0 AND 100),
    CONSTRAINT ck_analysis_results_career_score CHECK (career_similarity_score BETWEEN 0 AND 100),
    CONSTRAINT ck_analysis_results_preference_score CHECK (preference_score BETWEEN 0 AND 100),
    CONSTRAINT ck_analysis_results_eligibility
        CHECK (eligibility_status IN ('ELIGIBLE', 'CONDITIONAL', 'NOT_ELIGIBLE', 'UNKNOWN'))
);

CREATE TABLE analysis_result_reasons (
    reason_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id              BIGINT NOT NULL,
    reason_type            VARCHAR(20) NOT NULL,
    reason_content         TEXT NOT NULL,
    sort_order             SMALLINT NOT NULL DEFAULT 1,
    CONSTRAINT fk_analysis_result_reasons_result
        FOREIGN KEY (result_id) REFERENCES analysis_country_results (result_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_analysis_result_reasons_type
        CHECK (reason_type IN ('STRENGTH', 'IMPROVEMENT')),
    CONSTRAINT ck_analysis_result_reasons_sort CHECK (sort_order >= 1)
);

CREATE TABLE occupations (
    occupation_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code             VARCHAR(3) NOT NULL,
    classification_system    VARCHAR(20) NOT NULL,
    occupation_code          VARCHAR(30) NOT NULL,
    occupation_title         VARCHAR(200) NOT NULL,
    occupation_description   TEXT,
    skill_level              VARCHAR(50),
    official_url             TEXT,
    is_active                BOOLEAN NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_occupations_country
        FOREIGN KEY (country_code) REFERENCES countries (country_code)
        ON DELETE RESTRICT,
    CONSTRAINT uq_occupations_code
        UNIQUE (country_code, classification_system, occupation_code),
    CONSTRAINT ck_occupations_system
        CHECK (classification_system IN ('NOC', 'ANZSCO', 'SOC'))
);

CREATE TABLE analysis_occupation_matches (
    match_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id            BIGINT NOT NULL,
    occupation_id        BIGINT NOT NULL,
    similarity_score     NUMERIC(5, 2) NOT NULL,
    match_rank           SMALLINT NOT NULL,
    match_reason         TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_occupation_matches_result
        FOREIGN KEY (result_id) REFERENCES analysis_country_results (result_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_occupation_matches_occupation
        FOREIGN KEY (occupation_id) REFERENCES occupations (occupation_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_occupation_matches_result_occupation UNIQUE (result_id, occupation_id),
    CONSTRAINT uq_occupation_matches_result_rank UNIQUE (result_id, match_rank),
    CONSTRAINT ck_occupation_matches_score CHECK (similarity_score BETWEEN 0 AND 100),
    CONSTRAINT ck_occupation_matches_rank CHECK (match_rank >= 1)
);

CREATE TABLE chat_sessions (
    session_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    analysis_id         BIGINT,
    visa_program_id     BIGINT,
    session_title       VARCHAR(200),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_sessions_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_chat_sessions_analysis
        FOREIGN KEY (analysis_id) REFERENCES analyses (analysis_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_chat_sessions_visa_program
        FOREIGN KEY (visa_program_id) REFERENCES visa_programs (visa_program_id)
        ON DELETE SET NULL
);

CREATE TABLE chat_messages (
    message_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id          BIGINT NOT NULL,
    message_role        VARCHAR(20) NOT NULL,
    message_content     TEXT NOT NULL,
    answerable          BOOLEAN,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_messages_session
        FOREIGN KEY (session_id) REFERENCES chat_sessions (session_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_chat_messages_role
        CHECK (message_role IN ('USER', 'ASSISTANT'))
);

CREATE TABLE policy_documents (
    document_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code        VARCHAR(3) NOT NULL,
    visa_program_id     BIGINT,
    document_title      VARCHAR(300) NOT NULL,
    document_type       VARCHAR(50),
    source_url          TEXT NOT NULL,
    effective_date      DATE,
    verified_at         TIMESTAMPTZ NOT NULL,
    content_hash        VARCHAR(128),
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_policy_documents_country
        FOREIGN KEY (country_code) REFERENCES countries (country_code)
        ON DELETE RESTRICT,
    CONSTRAINT fk_policy_documents_visa_program
        FOREIGN KEY (visa_program_id) REFERENCES visa_programs (visa_program_id)
        ON DELETE SET NULL,
    CONSTRAINT uq_policy_documents_source_url UNIQUE (source_url)
);

CREATE TABLE policy_chunks (
    chunk_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id         BIGINT NOT NULL,
    chunk_index         INTEGER NOT NULL,
    section_title       VARCHAR(300),
    chunk_content       TEXT NOT NULL,
    token_count         INTEGER,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_policy_chunks_document
        FOREIGN KEY (document_id) REFERENCES policy_documents (document_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_policy_chunks_document_index UNIQUE (document_id, chunk_index),
    CONSTRAINT ck_policy_chunks_index CHECK (chunk_index >= 0),
    CONSTRAINT ck_policy_chunks_token_count CHECK (token_count IS NULL OR token_count >= 0)
);

CREATE TABLE chat_message_sources (
    source_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id          BIGINT NOT NULL,
    chunk_id            BIGINT NOT NULL,
    relevance_score     NUMERIC(7, 6),
    quoted_text         TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_message_sources_message
        FOREIGN KEY (message_id) REFERENCES chat_messages (message_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_chat_message_sources_chunk
        FOREIGN KEY (chunk_id) REFERENCES policy_chunks (chunk_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_chat_message_sources_message_chunk UNIQUE (message_id, chunk_id),
    CONSTRAINT ck_chat_message_sources_relevance
        CHECK (relevance_score IS NULL OR relevance_score BETWEEN 0 AND 1)
);

CREATE INDEX idx_visa_programs_country ON visa_programs (country_code);
CREATE INDEX idx_analyses_user_requested ON analyses (user_id, requested_at DESC);
CREATE INDEX idx_analyses_status ON analyses (analysis_status);
CREATE INDEX idx_analysis_results_analysis ON analysis_country_results (analysis_id);
CREATE INDEX idx_analysis_reasons_result ON analysis_result_reasons (result_id);
CREATE INDEX idx_occupations_country_title ON occupations (country_code, occupation_title);
CREATE INDEX idx_occupation_matches_result ON analysis_occupation_matches (result_id);
CREATE INDEX idx_chat_sessions_user_updated ON chat_sessions (user_id, updated_at DESC);
CREATE INDEX idx_chat_messages_session_created ON chat_messages (session_id, created_at);
CREATE INDEX idx_policy_documents_country_program ON policy_documents (country_code, visa_program_id);
CREATE INDEX idx_policy_chunks_document ON policy_chunks (document_id);
CREATE INDEX idx_chat_message_sources_message ON chat_message_sources (message_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_user_profiles_updated_at
BEFORE UPDATE ON user_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_chat_sessions_updated_at
BEFORE UPDATE ON chat_sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO countries (country_code, country_name_ko, country_name_en)
VALUES
    ('CAN', '캐나다', 'Canada'),
    ('AUS', '호주', 'Australia'),
    ('GBR', '영국', 'United Kingdom');

INSERT INTO visa_programs (
    country_code,
    program_code,
    program_name_ko,
    program_name_en
)
VALUES
    ('CAN', 'CA_EXPRESS_ENTRY_FSW', 'Express Entry 연방 전문인력 프로그램', 'Express Entry - Federal Skilled Worker Program'),
    ('AUS', 'AU_SKILLED_INDEPENDENT_189', '기술독립 비자 Subclass 189', 'Skilled Independent Visa - Subclass 189'),
    ('GBR', 'UK_SKILLED_WORKER', 'Skilled Worker 비자', 'Skilled Worker Visa');
