-- =========================================================
-- Living Abroad MVP
-- Flyway migration: V3__add_visa_rules.sql
-- Rule-engine table for visa eligibility scoring (F-AI-001~003).
-- Rules are DB-managed (not ML) per country/visa/factor, with each
-- tier scoring a range [min_value, max_value] (either bound may be
-- NULL for an open-ended tier). The evaluator picks the highest-
-- scoring tier whose range contains the applicant's value.
-- =========================================================

CREATE TABLE visa_rules (
    rule_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code        VARCHAR(3) NOT NULL,
    visa_program_id     BIGINT NOT NULL,
    factor_code         VARCHAR(30) NOT NULL,
    operator            VARCHAR(10) NOT NULL,
    min_value           NUMERIC(10, 2),
    max_value           NUMERIC(10, 2),
    score               SMALLINT NOT NULL,
    description         TEXT NOT NULL,
    source_url          TEXT,
    effective_from      DATE,
    effective_to        DATE,
    last_verified_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_visa_rules_country
        FOREIGN KEY (country_code) REFERENCES countries (country_code)
        ON DELETE RESTRICT,
    CONSTRAINT fk_visa_rules_visa_program
        FOREIGN KEY (visa_program_id) REFERENCES visa_programs (visa_program_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_visa_rules_operator
        CHECK (operator IN ('>=', '<=', 'BETWEEN', '='))
);

CREATE INDEX idx_visa_rules_visa_program ON visa_rules (visa_program_id);
CREATE INDEX idx_visa_rules_factor ON visa_rules (visa_program_id, factor_code);

-- EDUCATION factor values are ordinal, matching UserProfile.education:
-- HIGH_SCHOOL=1, ASSOCIATE=2, BACHELOR=3, MASTER=4, DOCTOR=5

-- =========================================================
-- CAN: Express Entry - Federal Skilled Worker (CA_EXPRESS_ENTRY_FSW)
-- Simplified from IRCC's Comprehensive Ranking System core/human-capital factors.
-- =========================================================

INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'AGE', 'BETWEEN', 18, 29, 12, '나이 18~29세: 최고 구간', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/criteria-comprehensive-ranking-system.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'AGE', 'BETWEEN', 30, 34, 10, '나이 30~34세', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/criteria-comprehensive-ranking-system.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'AGE', 'BETWEEN', 35, 39, 8, '나이 35~39세', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/criteria-comprehensive-ranking-system.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'AGE', 'BETWEEN', 40, 44, 6, '나이 40~44세', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/criteria-comprehensive-ranking-system.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'AGE', 'BETWEEN', 45, NULL, 0, '나이 45세 이상: 연령 가점 없음', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/criteria-comprehensive-ranking-system.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';

INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'EDUCATION', '>=', 1, NULL, 5, '고졸: 학력 가점 낮음', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/criteria-comprehensive-ranking-system.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'EDUCATION', '>=', 2, NULL, 15, '전문학사 이상', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/criteria-comprehensive-ranking-system.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'EDUCATION', '>=', 3, NULL, 21, '학사 학위 보유', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/criteria-comprehensive-ranking-system.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'EDUCATION', '>=', 4, NULL, 23, '석사 학위 보유', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/criteria-comprehensive-ranking-system.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'EDUCATION', '>=', 5, NULL, 25, '박사 학위 보유', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/criteria-comprehensive-ranking-system.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';

INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'EXPERIENCE_YEARS', '>=', 1, NULL, 9, '관련 경력 1년 이상', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/federal-skilled-workers.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'EXPERIENCE_YEARS', '>=', 2, NULL, 11, '관련 경력 2년 이상', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/federal-skilled-workers.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'EXPERIENCE_YEARS', '>=', 4, NULL, 13, '관련 경력 4년 이상', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/federal-skilled-workers.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'EXPERIENCE_YEARS', '>=', 6, NULL, 15, '관련 경력 6년 이상', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/eligibility/federal-skilled-workers.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';

INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'LANGUAGE_SCORE', '>=', 6.0, NULL, 16, '언어 점수 CLB 7 상당(IELTS 6.0)', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/documents/language-requirements.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'LANGUAGE_SCORE', '>=', 6.5, NULL, 20, '언어 점수 CLB 8 상당(IELTS 6.5)', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/documents/language-requirements.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'CAN', vp.visa_program_id, 'LANGUAGE_SCORE', '>=', 7.0, NULL, 24, '언어 점수 CLB 9 이상(IELTS 7.0)', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/documents/language-requirements.html', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'CA_EXPRESS_ENTRY_FSW';

-- =========================================================
-- AUS: Skilled Independent Visa Subclass 189 (AU_SKILLED_INDEPENDENT_189)
-- Simplified from the General Skilled Migration points test (pass mark 65).
-- =========================================================

INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'AGE', 'BETWEEN', 18, 24, 25, '나이 18~24세', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'AGE', 'BETWEEN', 25, 32, 30, '나이 25~32세: 최고 구간', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'AGE', 'BETWEEN', 33, 39, 25, '나이 33~39세', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'AGE', 'BETWEEN', 40, 44, 15, '나이 40~44세', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'AGE', 'BETWEEN', 45, NULL, 0, '나이 45세 이상: Subclass 189은 일반적으로 45세 미만 지원 가능', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';

INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'EDUCATION', '>=', 1, NULL, 0, '고졸: 학력 가점 없음', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'EDUCATION', '>=', 2, NULL, 10, '전문학사(디플로마) 이상', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'EDUCATION', '>=', 3, NULL, 15, '학사 학위 보유', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'EDUCATION', '>=', 5, NULL, 20, '박사 학위 보유', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';

INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'EXPERIENCE_YEARS', '>=', 3, NULL, 5, '해외 경력 3년 이상', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'EXPERIENCE_YEARS', '>=', 5, NULL, 10, '해외 경력 5년 이상', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'EXPERIENCE_YEARS', '>=', 8, NULL, 15, '해외 경력 8년 이상', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';

INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'LANGUAGE_SCORE', '>=', 6.0, NULL, 0, 'Competent English(IELTS 6.0): 최소 기준 충족', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'LANGUAGE_SCORE', '>=', 7.0, NULL, 10, 'Proficient English(IELTS 7.0)', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'AUS', vp.visa_program_id, 'LANGUAGE_SCORE', '>=', 8.0, NULL, 20, 'Superior English(IELTS 8.0 이상)', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189/points-table', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'AU_SKILLED_INDEPENDENT_189';

-- =========================================================
-- GBR: Skilled Worker Visa (UK_SKILLED_WORKER)
-- Requires a licensed sponsor + job offer, which this service cannot
-- verify from user input alone — always flagged for manual confirmation.
-- =========================================================

INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'GBR', vp.visa_program_id, 'EDUCATION', '>=', 1, 1, 0, '고졸: RQF 3 이상 직무 자격 요건 확인 필요', 'https://www.gov.uk/skilled-worker-visa', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'UK_SKILLED_WORKER';
INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'GBR', vp.visa_program_id, 'EDUCATION', '>=', 2, NULL, 10, '전문학사 이상: RQF 3(A-level 상당) 요건 충족 가능성 높음', 'https://www.gov.uk/skilled-worker-visa', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'UK_SKILLED_WORKER';

INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'GBR', vp.visa_program_id, 'LANGUAGE_SCORE', '>=', 4.0, NULL, 10, '영어 요건 CEFR B1(IELTS 4.0) 상당 충족', 'https://www.gov.uk/skilled-worker-visa/knowledge-of-english', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'UK_SKILLED_WORKER';

INSERT INTO visa_rules (country_code, visa_program_id, factor_code, operator, min_value, max_value, score, description, source_url, last_verified_at)
SELECT 'GBR', vp.visa_program_id, 'SPONSOR_REQUIRED', '=', 1, 1, 0, '공인 스폰서의 고용 제안(CoS) 필요 — 본 서비스 입력만으로는 확인 불가', 'https://www.gov.uk/skilled-worker-visa/your-job', '2026-07-17'
FROM visa_programs vp WHERE vp.program_code = 'UK_SKILLED_WORKER';
