-- 다른 토큰 테이블들(email_verification_tokens, refresh_tokens, password_reset_tokens)과 달리
-- 해시가 아니라 원문 토큰을 그대로 저장한다. 이 토큰은 계정 접근 권한을 증명하는 자격증명이 아니라
-- 이미 개인정보가 없는(이름/이메일 미포함) 분석 결과를 가리키는 공개 조회용 슬러그이기 때문이다.
CREATE TABLE analysis_share_tokens (
    share_token_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id         BIGINT NOT NULL,
    share_token         VARCHAR(64) NOT NULL,
    revoked_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_analysis_share_tokens_share_token UNIQUE (share_token),
    CONSTRAINT fk_analysis_share_tokens_analysis FOREIGN KEY (analysis_id) REFERENCES analyses(analysis_id) ON DELETE CASCADE
);

CREATE INDEX idx_analysis_share_tokens_analysis ON analysis_share_tokens(analysis_id);
